
# medications_data.py

ELDERLY_MEDS = [
    # Cardiovascular medications
    ('Lipitor', 'Atorvastatin', 'High cholesterol, cardiovascular disease prevention'),
    ('Crestor', 'Rosuvastatin', 'High cholesterol, heart disease prevention'),
    ('Zocor', 'Simvastatin', 'High cholesterol'),
    ('Pravachol', 'Pravastatin', 'High cholesterol'),
    ('Livalo', 'Pitavastatin', 'High cholesterol'),
    ('Lisinopril', 'Lisinopril', 'High blood pressure, heart failure'),
    ('Norvasc', 'Amlodipine', 'High blood pressure, angina'),
    ('Lotrel', 'Amlodipine/Benazepril', 'High blood pressure'),
    ('Toprol XL', 'Metoprolol', 'High blood pressure, heart failure'),
    ('Coreg', 'Carvedilol', 'Heart failure, high blood pressure'),
    ('Losartan', 'Losartan', 'High blood pressure'),
    ('Valsartan', 'Valsartan', 'High blood pressure, heart failure'),
    ('Diovan', 'Valsartan', 'High blood pressure, heart failure'),
    ('Cozaar', 'Losartan', 'High blood pressure'),
    ('Avapro', 'Irbesartan', 'High blood pressure'),
    ('Atacand', 'Candesartan', 'High blood pressure'),
    ('Micardis', 'Telmisartan', 'High blood pressure'),
    ('Benicar', 'Olmesartan', 'High blood pressure'),
    ('Prinivil', 'Lisinopril', 'High blood pressure, heart failure'),
    ('Zestril', 'Lisinopril', 'High blood pressure, heart failure'),
    ('Altace', 'Ramipril', 'High blood pressure, heart failure'),
    ('Vasotec', 'Enalapril', 'High blood pressure, heart failure'),
    ('Capoten', 'Captopril', 'High blood pressure, heart failure'),
    ('Monopril', 'Fosinopril', 'High blood pressure'),
    ('Accupril', 'Quinapril', 'High blood pressure'),
    ('Univasc', 'Moexipril', 'High blood pressure'),
    ('Mavik', 'Trandolapril', 'High blood pressure'),
    ('Plavix', 'Clopidogrel', 'Blood clot prevention'),
    ('Coumadin', 'Warfarin', 'Blood clot prevention'),
    ('Eliquis', 'Apixaban', 'Blood clot prevention, atrial fibrillation'),
    ('Xarelto', 'Rivaroxaban', 'Blood clot prevention'),
    ('Pradaxa', 'Dabigatran', 'Blood clot prevention, atrial fibrillation'),
    ('Savaysa', 'Edoxaban', 'Blood clot prevention'),
    ('Brilinta', 'Ticagrelor', 'Blood clot prevention'),
    ('Effient', 'Prasugrel', 'Blood clot prevention'),
    ('Lanoxin', 'Digoxin', 'Heart failure, atrial fibrillation'),
    ('Tambocor', 'Flecainide', 'Irregular heartbeat'),
    ('Rythmol', 'Propafenone', 'Irregular heartbeat'),
    ('Multaq', 'Dronedarone', 'Atrial fibrillation'),
    ('Tikosyn', 'Dofetilide', 'Atrial fibrillation'),
    ('Cordarone', 'Amiodarone', 'Irregular heartbeat'),
    ('Pacerone', 'Amiodarone', 'Irregular heartbeat'),
    ('Sotalol', 'Sotalol', 'Irregular heartbeat'),
    ('Betapace', 'Sotalol', 'Irregular heartbeat'),
    ('Quinidine', 'Quinidine', 'Irregular heartbeat'),
    ('Procainamide', 'Procainamide', 'Irregular heartbeat'),
    ('Disopyramide', 'Disopyramide', 'Irregular heartbeat'),
    ('Propranolol', 'Propranolol', 'High blood pressure, heart rhythm'),
    ('Inderal', 'Propranolol', 'High blood pressure, migraine prevention'),
    ('Tenormin', 'Atenolol', 'High blood pressure'),
    ('Lopressor', 'Metoprolol', 'High blood pressure, heart failure'),
    ('Zebeta', 'Bisoprolol', 'Heart failure'),
    ('Bystolic', 'Nebivolol', 'High blood pressure'),
    ('Sectral', 'Acebutolol', 'High blood pressure'),
    ('Kerlone', 'Betaxolol', 'High blood pressure'),
    ('Levatol', 'Penbutolol', 'High blood pressure'),
    ('Visken', 'Pindolol', 'High blood pressure'),
    ('Blocadren', 'Timolol', 'High blood pressure'),
    ('Corgard', 'Nadolol', 'High blood pressure'),
    ('Trandate', 'Labetalol', 'High blood pressure'),
    ('Normodyne', 'Labetalol', 'High blood pressure'),
    ('Cardura', 'Doxazosin', 'High blood pressure, enlarged prostate'),
    ('Hytrin', 'Terazosin', 'High blood pressure, enlarged prostate'),
    ('Minipress', 'Prazosin', 'High blood pressure'),
    ('Uroxatral', 'Alfuzosin', 'Enlarged prostate'),
    ('Flomax', 'Tamsulosin', 'Enlarged prostate'),
    ('Rapaflo', 'Silodosin', 'Enlarged prostate'),
    ('Catapres', 'Clonidine', 'High blood pressure'),
    ('Tenex', 'Guanfacine', 'High blood pressure'),
    ('Wytensin', 'Guanabenz', 'High blood pressure'),
    ('Methyldopa', 'Methyldopa', 'High blood pressure'),
    ('Aldactone', 'Spironolactone', 'Heart failure, high blood pressure'),
    ('Inspra', 'Eplerenone', 'Heart failure, high blood pressure'),
    ('Lasix', 'Furosemide', 'Fluid retention, heart failure'),
    ('Bumex', 'Bumetanide', 'Fluid retention'),
    ('Demadex', 'Torsemide', 'Fluid retention'),
    ('Edecrin', 'Ethacrynic acid', 'Fluid retention'),
    ('Hydrochlorothiazide', 'Hydrochlorothiazide', 'High blood pressure, fluid retention'),
    ('Microzide', 'Hydrochlorothiazide', 'High blood pressure'),
    ('Chlorthalidone', 'Chlorthalidone', 'High blood pressure'),
    ('Indapamide', 'Indapamide', 'High blood pressure'),
    ('Zaroxolyn', 'Metolazone', 'Fluid retention'),
    ('Midamor', 'Amiloride', 'Fluid retention'),
    ('Dyrenium', 'Triamterene', 'Fluid retention'),
    ('Maxzide', 'Triamterene/HCTZ', 'High blood pressure'),
    ('Dyazide', 'Triamterene/HCTZ', 'High blood pressure'),
    ('Aldactazide', 'Spironolactone/HCTZ', 'High blood pressure'),
    ('Nitrostat', 'Nitroglycerin', 'Chest pain, angina'),
    ('Imdur', 'Isosorbide mononitrate', 'Chest pain prevention'),
    ('Isordil', 'Isosorbide dinitrate', 'Chest pain prevention'),
    ('Ranexa', 'Ranolazine', 'Chronic angina'),
    ('Norpace', 'Disopyramide', 'Heart rhythm disorders'),
    ('Vasodilan', 'Isoxsuprine', 'Circulation problems'),
    ('Pentoxifylline', 'Pentoxifylline', 'Circulation problems'),
    ('Pletal', 'Cilostazol', 'Circulation problems'),

    # Diabetes medications
    ('Metformin', 'Metformin', 'Type 2 diabetes'),
    ('Glucophage', 'Metformin', 'Type 2 diabetes'),
    ('Januvia', 'Sitagliptin', 'Type 2 diabetes'),
    ('Onglyza', 'Saxagliptin', 'Type 2 diabetes'),
    ('Tradjenta', 'Linagliptin', 'Type 2 diabetes'),
    ('Nesina', 'Alogliptin', 'Type 2 diabetes'),
    ('Invokana', 'Canagliflozin', 'Type 2 diabetes'),
    ('Farxiga', 'Dapagliflozin', 'Type 2 diabetes'),
    ('Jardiance', 'Empagliflozin', 'Type 2 diabetes, heart failure'),
    ('Steglatro', 'Ertugliflozin', 'Type 2 diabetes'),
    ('Amaryl', 'Glimepiride', 'Type 2 diabetes'),
    ('Glucotrol', 'Glipizide', 'Type 2 diabetes'),
    ('Micronase', 'Glyburide', 'Type 2 diabetes'),
    ('DiaBeta', 'Glyburide', 'Type 2 diabetes'),
    ('Glynase', 'Glyburide', 'Type 2 diabetes'),
    ('Prandin', 'Repaglinide', 'Type 2 diabetes'),
    ('Starlix', 'Nateglinide', 'Type 2 diabetes'),
    ('Actos', 'Pioglitazone', 'Type 2 diabetes'),
    ('Avandia', 'Rosiglitazone', 'Type 2 diabetes'),
    ('Precose', 'Acarbose', 'Type 2 diabetes'),
    ('Glyset', 'Miglitol', 'Type 2 diabetes'),
    ('Insulin', 'Insulin', 'Type 1 and 2 diabetes'),
    ('Lantus', 'Insulin glargine', 'Long-acting insulin'),
    ('Levemir', 'Insulin detemir', 'Long-acting insulin'),
    ('Toujeo', 'Insulin glargine', 'Long-acting insulin'),
    ('Tresiba', 'Insulin degludec', 'Long-acting insulin'),
    ('Humalog', 'Insulin lispro', 'Fast-acting insulin'),
    ('Novolog', 'Insulin aspart', 'Fast-acting insulin'),
    ('Apidra', 'Insulin glulisine', 'Fast-acting insulin'),
    ('Fiasp', 'Insulin aspart', 'Fast-acting insulin'),
    ('Humulin', 'Human insulin', 'Diabetes'),
    ('Novolin', 'Human insulin', 'Diabetes'),
    ('Victoza', 'Liraglutide', 'Type 2 diabetes'),
    ('Ozempic', 'Semaglutide', 'Type 2 diabetes'),
    ('Trulicity', 'Dulaglutide', 'Type 2 diabetes'),
    ('Bydureon', 'Exenatide', 'Type 2 diabetes'),
    ('Byetta', 'Exenatide', 'Type 2 diabetes'),
    ('Symlinpen', 'Pramlintide', 'Diabetes'),

    # Bone health medications
    ('Fosamax', 'Alendronate', 'Osteoporosis'),
    ('Actonel', 'Risedronate', 'Osteoporosis'),
    ('Boniva', 'Ibandronate', 'Osteoporosis'),
    ('Reclast', 'Zoledronic acid', 'Osteoporosis'),
    ('Atelvia', 'Risedronate', 'Osteoporosis'),
    ('Binosto', 'Alendronate', 'Osteoporosis'),
    ('Prolia', 'Denosumab', 'Osteoporosis'),
    ('Forteo', 'Teriparatide', 'Osteoporosis'),
    ('Tymlos', 'Abaloparatide', 'Osteoporosis'),
    ('Evenity', 'Romosozumab', 'Osteoporosis'),
    ('Miacalcin', 'Calcitonin', 'Osteoporosis'),
    ('Fortical', 'Calcitonin', 'Osteoporosis'),
    ('Raloxifene', 'Raloxifene', 'Osteoporosis'),
    ('Evista', 'Raloxifene', 'Osteoporosis'),

    # Pain and inflammation medications
    ('Tylenol', 'Acetaminophen', 'Pain relief, fever'),
    ('Advil', 'Ibuprofen', 'Pain, inflammation, fever'),
    ('Motrin', 'Ibuprofen', 'Pain, inflammation, fever'),
    ('Aleve', 'Naproxen', 'Pain, inflammation'),
    ('Naprosyn', 'Naproxen', 'Pain, inflammation'),
    ('Anaprox', 'Naproxen', 'Pain, inflammation'),
    ('Celebrex', 'Celecoxib', 'Arthritis pain, inflammation'),
    ('Voltaren', 'Diclofenac', 'Arthritis pain, inflammation'),
    ('Mobic', 'Meloxicam', 'Arthritis pain, inflammation'),
    ('Indocin', 'Indomethacin', 'Arthritis, inflammation'),
    ('Relafen', 'Nabumetone', 'Arthritis'),
    ('Feldene', 'Piroxicam', 'Arthritis'),
    ('Lodine', 'Etodolac', 'Arthritis'),
    ('Daypro', 'Oxaprozin', 'Arthritis'),
    ('Clinoril', 'Sulindac', 'Arthritis'),
    ('Tolectin', 'Tolmetin', 'Arthritis'),
    ('Ansaid', 'Flurbiprofen', 'Arthritis'),
    ('Orudis', 'Ketoprofen', 'Arthritis'),
    ('Actron', 'Ketoprofen', 'Pain, inflammation'),
    ('Arthrotec', 'Diclofenac/Misoprostol', 'Arthritis'),
    ('Aspirin', 'Aspirin', 'Pain, inflammation, heart protection'),
    ('Ecotrin', 'Aspirin', 'Heart protection, pain'),
    ('Bufferin', 'Aspirin', 'Pain relief'),
    ('Excedrin', 'Aspirin/Acetaminophen/Caffeine', 'Headache, pain'),

    # Mental health medications
    ('Prozac', 'Fluoxetine', 'Depression, anxiety'),
    ('Zoloft', 'Sertraline', 'Depression, anxiety'),
    ('Paxil', 'Paroxetine', 'Depression, anxiety'),
    ('Lexapro', 'Escitalopram', 'Depression, anxiety'),
    ('Celexa', 'Citalopram', 'Depression'),
    ('Effexor', 'Venlafaxine', 'Depression, anxiety'),
    ('Cymbalta', 'Duloxetine', 'Depression, anxiety, neuropathy'),
    ('Pristiq', 'Desvenlafaxine', 'Depression'),
    ('Wellbutrin', 'Bupropion', 'Depression, smoking cessation'),
    ('Zyban', 'Bupropion', 'Smoking cessation'),
    ('Remeron', 'Mirtazapine', 'Depression'),
    ('Desyrel', 'Trazodone', 'Depression, insomnia'),
    ('Elavil', 'Amitriptyline', 'Depression, neuropathy'),
    ('Pamelor', 'Nortriptyline', 'Depression'),
    ('Sinequan', 'Doxepin', 'Depression, anxiety'),
    ('Norpramin', 'Desipramine', 'Depression'),
    ('Aventyl', 'Nortriptyline', 'Depression'),
    ('Vivactil', 'Protriptyline', 'Depression'),
    ('Surmontil', 'Trimipramine', 'Depression'),
    ('Anafranil', 'Clomipramine', 'OCD, depression'),
    ('Nardil', 'Phenelzine', 'Depression'),
    ('Parnate', 'Tranylcypromine', 'Depression'),
    ('Marplan', 'Isocarboxazid', 'Depression'),
    ('Emsam', 'Selegiline', 'Depression'),
    ('Abilify', 'Aripiprazole', 'Depression, bipolar disorder, schizophrenia'),
    ('Seroquel', 'Quetiapine', 'Bipolar disorder, schizophrenia'),
    ('Risperdal', 'Risperidone', 'Schizophrenia, bipolar disorder'),
    ('Zyprexa', 'Olanzapine', 'Bipolar disorder, schizophrenia'),
    ('Geodon', 'Ziprasidone', 'Bipolar disorder, schizophrenia'),
    ('Latuda', 'Lurasidone', 'Bipolar disorder, schizophrenia'),
    ('Rexulti', 'Brexpiprazole', 'Depression, schizophrenia'),
    ('Vraylar', 'Cariprazine', 'Bipolar disorder, schizophrenia'),
    ('Haldol', 'Haloperidol', 'Schizophrenia, agitation'),
    ('Thorazine', 'Chlorpromazine', 'Schizophrenia'),
    ('Prolixin', 'Fluphenazine', 'Schizophrenia'),
    ('Navane', 'Thiothixene', 'Schizophrenia'),
    ('Mellaril', 'Thioridazine', 'Schizophrenia'),
    ('Stelazine', 'Trifluoperazine', 'Schizophrenia'),
    ('Lithium', 'Lithium', 'Bipolar disorder'),
    ('Lithobid', 'Lithium', 'Bipolar disorder'),
    ('Depakote', 'Divalproex', 'Bipolar disorder, seizures'),
    ('Tegretol', 'Carbamazepine', 'Bipolar disorder, seizures'),
    ('Lamictal', 'Lamotrigine', 'Bipolar disorder, seizures'),
    ('Trileptal', 'Oxcarbazepine', 'Bipolar disorder, seizures'),
    ('Neurontin', 'Gabapentin', 'Neuropathy, seizures'),
    ('Lyrica', 'Pregabalin', 'Neuropathy, fibromyalgia'),

    # Anxiety and sleep medications
    ('Xanax', 'Alprazolam', 'Anxiety, panic disorder'),
    ('Ativan', 'Lorazepam', 'Anxiety, insomnia'),
    ('Valium', 'Diazepam', 'Anxiety, muscle spasms'),
    ('Klonopin', 'Clonazepam', 'Anxiety, seizures'),
    ('Librium', 'Chlordiazepoxide', 'Anxiety'),
    ('Serax', 'Oxazepam', 'Anxiety'),
    ('Tranxene', 'Clorazepate', 'Anxiety'),
    ('Centrax', 'Prazepam', 'Anxiety'),
    ('Dalmane', 'Flurazepam', 'Insomnia'),
    ('Halcion', 'Triazolam', 'Insomnia'),
    ('Restoril', 'Temazepam', 'Insomnia'),
    ('ProSom', 'Estazolam', 'Insomnia'),
    ('Versed', 'Midazolam', 'Sedation'),
    ('Ambien', 'Zolpidem', 'Insomnia'),
    ('Lunesta', 'Eszopiclone', 'Insomnia'),
    ('Sonata', 'Zaleplon', 'Insomnia'),
    ('Rozerem', 'Ramelteon', 'Insomnia'),
    ('Belsomra', 'Suvorexant', 'Insomnia'),
    ('Silenor', 'Doxepin', 'Insomnia'),
    ('Buspar', 'Buspirone', 'Anxiety'),
    ('Vistaril', 'Hydroxyzine', 'Anxiety, itching'),
    ('Atarax', 'Hydroxyzine', 'Anxiety, itching'),

    # Thyroid medications
    ('Synthroid', 'Levothyroxine', 'Hypothyroidism'),
    ('Levoxyl', 'Levothyroxine', 'Hypothyroidism'),
    ('Unithroid', 'Levothyroxine', 'Hypothyroidism'),
    ('Levothroid', 'Levothyroxine', 'Hypothyroidism'),
    ('Tirosint', 'Levothyroxine', 'Hypothyroidism'),
    ('Armour Thyroid', 'Thyroid desiccated', 'Hypothyroidism'),
    ('Nature-Throid', 'Thyroid desiccated', 'Hypothyroidism'),
    ('WP Thyroid', 'Thyroid desiccated', 'Hypothyroidism'),
    ('Cytomel', 'Liothyronine', 'Hypothyroidism'),
    ('Triostat', 'Liothyronine', 'Hypothyroidism'),
    ('Thyrolar', 'Liotrix', 'Hypothyroidism'),
    ('Tapazole', 'Methimazole', 'Hyperthyroidism'),
    ('PTU', 'Propylthiouracil', 'Hyperthyroidism'),

    # Gastrointestinal medications
    ('Nexium', 'Esomeprazole', 'GERD, stomach ulcers'),
    ('Prilosec', 'Omeprazole', 'GERD, stomach ulcers'),
    ('Prevacid', 'Lansoprazole', 'GERD, stomach ulcers'),
    ('Protonix', 'Pantoprazole', 'GERD, stomach ulcers'),
    ('AcipHex', 'Rabeprazole', 'GERD, stomach ulcers'),
    ('Dexilant', 'Dexlansoprazole', 'GERD'),
    ('Zantac', 'Ranitidine', 'Heartburn, ulcers'),
    ('Pepcid', 'Famotidine', 'Heartburn, ulcers'),
    ('Tagamet', 'Cimetidine', 'Heartburn, ulcers'),
    ('Axid', 'Nizatidine', 'Heartburn, ulcers'),
    ('Carafate', 'Sucralfate', 'Stomach ulcers'),
    ('Cytotec', 'Misoprostol', 'Stomach ulcer prevention'),
    ('Reglan', 'Metoclopramide', 'Gastroparesis, nausea'),
    ('Domperidone', 'Domperidone', 'Gastroparesis'),
    ('Bentyl', 'Dicyclomine', 'IBS, stomach spasms'),
    ('Librax', 'Chlordiazepoxide/Clidinium', 'IBS, stomach spasms'),
    ('Donnatal', 'Belladonna/Phenobarbital', 'IBS, stomach spasms'),
    ('Hyoscyamine', 'Hyoscyamine', 'IBS, stomach spasms'),
    ('Levsin', 'Hyoscyamine', 'IBS, stomach spasms'),
    ('Lomotil', 'Diphenoxylate/Atropine', 'Diarrhea'),
    ('Imodium', 'Loperamide', 'Diarrhea'),
    ('Pepto-Bismol', 'Bismuth subsalicylate', 'Diarrhea, upset stomach'),
    ('Colace', 'Docusate', 'Constipation'),
    ('Senokot', 'Senna', 'Constipation'),
    ('Dulcolax', 'Bisacodyl', 'Constipation'),
    ('MiraLAX', 'Polyethylene glycol', 'Constipation'),
    ('Lactulose', 'Lactulose', 'Constipation'),
    ('Metamucil', 'Psyllium', 'Constipation, fiber supplement'),
    ('Citrucel', 'Methylcellulose', 'Constipation'),
    ('FiberCon', 'Polycarbophil', 'Constipation'),
    ('Linzess', 'Linaclotide', 'IBS with constipation'),
    ('Amitiza', 'Lubiprostone', 'Constipation'),
    ('Trulance', 'Plecanatide', 'Constipation'),
    ('Motegrity', 'Prucalopride', 'Constipation'),

    # Respiratory medications
    ('Advair', 'Fluticasone/Salmeterol', 'Asthma, COPD'),
    ('Symbicort', 'Budesonide/Formoterol', 'Asthma, COPD'),
    ('Dulera', 'Mometasone/Formoterol', 'Asthma'),
    ('Breo', 'Fluticasone/Vilanterol', 'Asthma, COPD'),
    ('Trelegy', 'Fluticasone/Umeclidinium/Vilanterol', 'COPD'),
    ('Spiriva', 'Tiotropium', 'COPD'),
    ('Combivent', 'Ipratropium/Albuterol', 'COPD'),
    ('DuoNeb', 'Ipratropium/Albuterol', 'COPD'),
    ('Atrovent', 'Ipratropium', 'COPD'),
    ('ProAir', 'Albuterol', 'Asthma, bronchospasm'),
    ('Ventolin', 'Albuterol', 'Asthma, bronchospasm'),
    ('Xopenex', 'Levalbuterol', 'Asthma, bronchospasm'),
    ('Maxair', 'Pirbuterol', 'Asthma'),
    ('Serevent', 'Salmeterol', 'Asthma, COPD'),
    ('Foradil', 'Formoterol', 'Asthma, COPD'),
    ('Perforomist', 'Formoterol', 'COPD'),
    ('Brovana', 'Arformoterol', 'COPD'),
    ('Striverdi', 'Olodaterol', 'COPD'),
    ('Arcapta', 'Indacaterol', 'COPD'),
    ('Tudorza', 'Aclidinium', 'COPD'),
    ('Seebri', 'Glycopyrrolate', 'COPD'),
    ('Lonhala', 'Glycopyrrolate', 'COPD'),
    ('Yupelri', 'Revefenacin', 'COPD'),
    ('Flovent', 'Fluticasone', 'Asthma'),
    ('Pulmicort', 'Budesonide', 'Asthma'),
    ('Asmanex', 'Mometasone', 'Asthma'),
    ('Qvar', 'Beclomethasone', 'Asthma'),
    ('Alvesco', 'Ciclesonide', 'Asthma'),
    ('Aerospan', 'Flunisolide', 'Asthma'),
    ('Singular', 'Montelukast', 'Asthma, allergies'),
    ('Accolate', 'Zafirlukast', 'Asthma'),
    ('Zyflo', 'Zileuton', 'Asthma'),
    ('Xolair', 'Omalizumab', 'Severe asthma'),
    ('Nucala', 'Mepolizumab', 'Severe asthma'),
    ('Cinqair', 'Reslizumab', 'Severe asthma'),
    ('Fasenra', 'Benralizumab', 'Severe asthma'),
    ('Dupixent', 'Dupilumab', 'Severe asthma'),
    ('Theo-Dur', 'Theophylline', 'Asthma, COPD'),
    ('Uniphyl', 'Theophylline', 'Asthma, COPD'),

    # Allergy medications
    ('Zyrtec', 'Cetirizine', 'Allergies'),
    ('Claritin', 'Loratadine', 'Allergies'),
    ('Allegra', 'Fexofenadine', 'Allergies'),
    ('Xyzal', 'Levocetirizine', 'Allergies'),
    ('Clarinex', 'Desloratadine', 'Allergies'),
    ('Benadryl', 'Diphenhydramine', 'Allergies, sleep aid'),
    ('Chlor-Trimeton', 'Chlorpheniramine', 'Allergies'),
    ('Tavist', 'Clemastine', 'Allergies'),
    ('Dimetane', 'Brompheniramine', 'Allergies'),
    ('Periactin', 'Cyproheptadine', 'Allergies, appetite stimulant'),
    ('Flonase', 'Fluticasone', 'Nasal allergies'),
    ('Nasacort', 'Triamcinolone', 'Nasal allergies'),
    ('Rhinocort', 'Budesonide', 'Nasal allergies'),
    ('Nasonex', 'Mometasone', 'Nasal allergies'),
    ('Omnaris', 'Ciclesonide', 'Nasal allergies'),
    ('Qnasl', 'Beclomethasone', 'Nasal allergies'),
    ('Zetonna', 'Ciclesonide', 'Nasal allergies'),
    ('Dymista', 'Azelastine/Fluticasone', 'Nasal allergies'),
    ('Astelin', 'Azelastine', 'Nasal allergies'),
    ('Astepro', 'Azelastine', 'Nasal allergies'),
    ('Patanase', 'Olopatadine', 'Nasal allergies'),

    # Neurological medications
    ('Aricept', 'Donepezil', 'Alzheimer\'s disease'),
    ('Exelon', 'Rivastigmine', 'Alzheimer\'s disease'),
    ('Razadyne', 'Galantamine', 'Alzheimer\'s disease'),
    ('Namenda', 'Memantine', 'Alzheimer\'s disease'),
    ('Namzaric', 'Donepezil/Memantine', 'Alzheimer\'s disease'),
    ('Sinemet', 'Carbidopa/Levodopa', 'Parkinson\'s disease'),
    ('Stalevo', 'Carbidopa/Levodopa/Entacapone', 'Parkinson\'s disease'),
    ('Rytary', 'Carbidopa/Levodopa', 'Parkinson\'s disease'),
    ('Duopa', 'Carbidopa/Levodopa', 'Parkinson\'s disease'),
    ('Inbrija', 'Levodopa', 'Parkinson\'s disease'),
    ('Mirapex', 'Pramipexole', 'Parkinson\'s disease, restless legs'),
    ('Requip', 'Ropinirole', 'Parkinson\'s disease, restless legs'),
    ('Neupro', 'Rotigotine', 'Parkinson\'s disease'),
    ('Parlodel', 'Bromocriptine', 'Parkinson\'s disease'),
    ('Permax', 'Pergolide', 'Parkinson\'s disease'),
    ('Apokyn', 'Apomorphine', 'Parkinson\'s disease'),
    ('Azilect', 'Rasagiline', 'Parkinson\'s disease'),
    ('Zelapar', 'Selegiline', 'Parkinson\'s disease'),
    ('Eldepryl', 'Selegiline', 'Parkinson\'s disease'),
    ('Comtan', 'Entacapone', 'Parkinson\'s disease'),
    ('Tasmar', 'Tolcapone', 'Parkinson\'s disease'),
    ('Artane', 'Trihexyphenidyl', 'Parkinson\'s disease'),
    ('Cogentin', 'Benztropine', 'Parkinson\'s disease'),
    ('Symmetrel', 'Amantadine', 'Parkinson\'s disease'),
    ('Gocovri', 'Amantadine', 'Parkinson\'s disease'),
    ('Osmolex', 'Amantadine', 'Parkinson\'s disease'),

    # Seizure medications
    ('Dilantin', 'Phenytoin', 'Seizures'),
    ('Tegretol', 'Carbamazepine', 'Seizures, bipolar disorder'),
    ('Depakote', 'Divalproex', 'Seizures, bipolar disorder'),
    ('Lamictal', 'Lamotrigine', 'Seizures, bipolar disorder'),
    ('Keppra', 'Levetiracetam', 'Seizures'),
    ('Trileptal', 'Oxcarbazepine', 'Seizures'),
    ('Topamax', 'Topiramate', 'Seizures, migraine prevention'),
    ('Neurontin', 'Gabapentin', 'Seizures, neuropathy'),
    ('Lyrica', 'Pregabalin', 'Seizures, neuropathy'),
    ('Zonegran', 'Zonisamide', 'Seizures'),
    ('Vimpat', 'Lacosamide', 'Seizures'),
    ('Banzel', 'Rufinamide', 'Seizures'),
    ('Fycompa', 'Perampanel', 'Seizures'),
    ('Aptiom', 'Eslicarbazepine', 'Seizures'),
    ('Briviact', 'Brivaracetam', 'Seizures'),
    ('Onfi', 'Clobazam', 'Seizures'),
    ('Sabril', 'Vigabatrin', 'Seizures'),
    ('Gabitril', 'Tiagabine', 'Seizures'),
    ('Felbamate', 'Felbamate', 'Seizures'),
    ('Phenobarbital', 'Phenobarbital', 'Seizures'),
    ('Primidone', 'Primidone', 'Seizures'),
    ('Ethosuximide', 'Ethosuximide', 'Absence seizures'),
    ('Zarontin', 'Ethosuximide', 'Absence seizures'),
    ('Celontin', 'Methsuximide', 'Absence seizures'),
    ('Peganone', 'Ethotoin', 'Seizures'),
    ('Mesantoin', 'Mephenytoin', 'Seizures'),
    ('Cerebyx', 'Fosphenytoin', 'Seizures'),
    ('Mysoline', 'Primidone', 'Seizures'),

    # Eye medications
    ('Timoptic', 'Timolol', 'Glaucoma'),
    ('Xalatan', 'Latanoprost', 'Glaucoma'),
    ('Lumigan', 'Bimatoprost', 'Glaucoma'),
    ('Travatan', 'Travoprost', 'Glaucoma'),
    ('Zioptan', 'Tafluprost', 'Glaucoma'),
    ('Vyzulta', 'Latanoprostene bunod', 'Glaucoma'),
    ('Rhopressa', 'Netarsudil', 'Glaucoma'),
    ('Rocklatan', 'Netarsudil/Latanoprost', 'Glaucoma'),
    ('Alphagan', 'Brimonidine', 'Glaucoma'),
    ('Iopidine', 'Apraclonidine', 'Glaucoma'),
    ('Trusopt', 'Dorzolamide', 'Glaucoma'),
    ('Azopt', 'Brinzolamide', 'Glaucoma'),
    ('Cosopt', 'Dorzolamide/Timolol', 'Glaucoma'),
    ('Combigan', 'Brimonidine/Timolol', 'Glaucoma'),
    ('Simbrinza', 'Brinzolamide/Brimonidine', 'Glaucoma'),
    ('Diamox', 'Acetazolamide', 'Glaucoma'),
    ('Neptazane', 'Methazolamide', 'Glaucoma'),
    ('Pilocarpine', 'Pilocarpine', 'Glaucoma'),
    ('Isopto Carpine', 'Pilocarpine', 'Glaucoma'),

    # Vitamins and supplements
    ('Vitamin D3', 'Cholecalciferol', 'Bone health, vitamin deficiency'),
    ('Vitamin B12', 'Cyanocobalamin', 'B12 deficiency, neuropathy'),
    ('Folic Acid', 'Folic acid', 'Folate deficiency, anemia'),
    ('Iron', 'Ferrous sulfate', 'Iron deficiency anemia'),
    ('Calcium', 'Calcium carbonate', 'Bone health'),
    ('Magnesium', 'Magnesium oxide', 'Magnesium deficiency'),
    ('Potassium', 'Potassium chloride', 'Potassium deficiency'),
    ('Multivitamin', 'Multivitamin', 'Nutritional supplement'),
    ('Omega-3', 'Fish oil', 'Heart health, inflammation'),
    ('Coenzyme Q10', 'Ubiquinone', 'Heart health, energy'),
    ('Probiotics', 'Lactobacillus', 'Digestive health'),
    ('Glucosamine', 'Glucosamine sulfate', 'Joint health'),
    ('Chondroitin', 'Chondroitin sulfate', 'Joint health'),
    ('Melatonin', 'Melatonin', 'Sleep disorders'),
    ('Biotin', 'Biotin', 'Hair, skin, nail health'),
    ('Vitamin C', 'Ascorbic acid', 'Immune support, antioxidant'),
    ('Vitamin E', 'Tocopherol', 'Antioxidant'),
    ('Zinc', 'Zinc sulfate', 'Immune support, wound healing'),
    ('Selenium', 'Selenium', 'Antioxidant'),
    ('Thiamine', 'Vitamin B1', 'B1 deficiency'),
    ('Riboflavin', 'Vitamin B2', 'B2 deficiency'),
    ('Niacin', 'Vitamin B3', 'Cholesterol, B3 deficiency'),
    ('Pyridoxine', 'Vitamin B6', 'B6 deficiency'),
    ('Pantothenic Acid', 'Vitamin B5', 'B5 deficiency'),

    # Hormones
    ('Premarin', 'Conjugated estrogens', 'Menopause symptoms'),
    ('Estrace', 'Estradiol', 'Menopause symptoms'),
    ('Climara', 'Estradiol', 'Menopause symptoms'),
    ('Vivelle', 'Estradiol', 'Menopause symptoms'),
    ('Provera', 'Medroxyprogesterone', 'Menopause, contraception'),
    ('Prometrium', 'Progesterone', 'Menopause'),
    ('Prempro', 'Estrogen/Progestin', 'Menopause symptoms'),
    ('Femhrt', 'Estrogen/Progestin', 'Menopause symptoms'),
    ('Activella', 'Estrogen/Progestin', 'Menopause symptoms'),
    ('Testosterone', 'Testosterone', 'Low testosterone'),
    ('AndroGel', 'Testosterone', 'Low testosterone'),
    ('Testim', 'Testosterone', 'Low testosterone'),
    ('Axiron', 'Testosterone', 'Low testosterone'),
    ('Fortesta', 'Testosterone', 'Low testosterone'),
    ('Vogelxo', 'Testosterone', 'Low testosterone'),

    # Migraine medications
    ('Imitrex', 'Sumatriptan', 'Migraine headaches'),
    ('Maxalt', 'Rizatriptan', 'Migraine headaches'),
    ('Zomig', 'Zolmitriptan', 'Migraine headaches'),
    ('Amerge', 'Naratriptan', 'Migraine headaches'),
    ('Relpax', 'Eletriptan', 'Migraine headaches'),
    ('Frova', 'Frovatriptan', 'Migraine headaches'),
    ('Axert', 'Almotriptan', 'Migraine headaches'),
    ('Treximet', 'Sumatriptan/Naproxen', 'Migraine headaches'),
    ('DHE', 'Dihydroergotamine', 'Migraine headaches'),
    ('Migranal', 'Dihydroergotamine', 'Migraine headaches'),
    ('Ergomar', 'Ergotamine', 'Migraine headaches'),
    ('Cafergot', 'Ergotamine/Caffeine', 'Migraine headaches'),
    ('Midrin', 'Isometheptene/Dichloralphenazone/Acetaminophen', 'Migraine headaches'),
    ('Fioricet', 'Butalbital/Acetaminophen/Caffeine', 'Tension headaches'),
    ('Fiorinal', 'Butalbital/Aspirin/Caffeine', 'Tension headaches'),
    ('Esgic', 'Butalbital/Acetaminophen/Caffeine', 'Tension headaches'),

    # Additional antibiotics commonly used in elderly care
    ('Amoxicillin', 'Amoxicillin', 'Bacterial infections, UTI'),
    ('Azithromycin', 'Azithromycin', 'Respiratory infections, skin infections'),
    ('Ciprofloxacin', 'Ciprofloxacin', 'UTI, respiratory infections'),
    ('Levofloxacin', 'Levofloxacin', 'Pneumonia, UTI, skin infections'),
    ('Cephalexin', 'Cephalexin', 'Skin infections, UTI'),
    ('Clindamycin', 'Clindamycin', 'Skin infections, dental infections'),
    ('Doxycycline', 'Doxycycline', 'Respiratory infections, skin conditions'),
    ('Trimethoprim-Sulfamethoxazole', 'TMP-SMX', 'UTI, MRSA infections'),
    ('Bactrim', 'Trimethoprim-Sulfamethoxazole', 'UTI, pneumonia'),
    ('Augmentin', 'Amoxicillin-Clavulanate', 'Respiratory infections, UTI'),
    ('Cefdinir', 'Cefdinir', 'Respiratory infections'),
    ('Nitrofurantoin', 'Nitrofurantoin', 'UTI prevention and treatment'),
    ('Macrobid', 'Nitrofurantoin', 'UTI'),
    ('Vancomycin', 'Vancomycin', 'MRSA infections, C. diff'),
    ('Metronidazole', 'Metronidazole', 'C. diff, anaerobic infections'),
    ('Flagyl', 'Metronidazole', 'Bacterial infections, C. diff'),
    ('Erythromycin', 'Erythromycin', 'Respiratory infections'),
    ('Clarithromycin', 'Clarithromycin', 'Respiratory infections'),
    ('Biaxin', 'Clarithromycin', 'Pneumonia, bronchitis'),

    # Antifungal medications
    ('Fluconazole', 'Fluconazole', 'Yeast infections, thrush'),
    ('Diflucan', 'Fluconazole', 'Vaginal yeast infections'),
    ('Nystatin', 'Nystatin', 'Oral thrush, skin yeast infections'),
    ('Ketoconazole', 'Ketoconazole', 'Fungal infections'),
    ('Itraconazole', 'Itraconazole', 'Fungal infections'),
    ('Sporanox', 'Itraconazole', 'Nail fungus, systemic fungal infections'),
    ('Terbinafine', 'Terbinafine', 'Nail fungus, athlete\'s foot'),
    ('Lamisil', 'Terbinafine', 'Fungal nail infections'),

    # Antiviral medications
    ('Acyclovir', 'Acyclovir', 'Herpes, shingles'),
    ('Zovirax', 'Acyclovir', 'Cold sores, shingles'),
    ('Valacyclovir', 'Valacyclovir', 'Herpes, shingles'),
    ('Valtrex', 'Valacyclovir', 'Herpes outbreaks, shingles'),
    ('Famciclovir', 'Famciclovir', 'Herpes, shingles'),
    ('Famvir', 'Famciclovir', 'Herpes zoster, genital herpes'),
    ('Oseltamivir', 'Oseltamivir', 'Influenza A and B'),
    ('Tamiflu', 'Oseltamivir', 'Flu treatment and prevention'),

    # Skin and wound care medications
    ('Mupirocin', 'Mupirocin', 'Bacterial skin infections'),
    ('Bactroban', 'Mupirocin', 'Impetigo, MRSA skin infections'),
    ('Silver Sulfadiazine', 'Silver Sulfadiazine', 'Burn treatment'),
    ('Silvadene', 'Silver Sulfadiazine', 'Burn wound care'),
    ('Bacitracin', 'Bacitracin', 'Minor cuts, wound prevention'),
    ('Neosporin', 'Neomycin/Polymyxin/Bacitracin', 'Minor wound care'),
    ('Hydrocortisone', 'Hydrocortisone', 'Skin inflammation, eczema'),
    ('Triamcinolone', 'Triamcinolone', 'Skin inflammation, allergies'),
    ('Kenalog', 'Triamcinolone', 'Skin conditions, joint injections'),
    ('Betamethasone', 'Betamethasone', 'Severe skin inflammation'),
    ('Clobetasol', 'Clobetasol', 'Severe skin conditions'),
    ('Temovate', 'Clobetasol', 'Psoriasis, severe dermatitis'),
    ('Calamine', 'Calamine', 'Itchy skin, minor irritation'),
    ('Zinc Oxide', 'Zinc Oxide', 'Diaper rash, skin protection'),

    # Additional medications commonly requested
    ('Probiotic', 'Lactobacillus/Bifidobacterium', 'Digestive health, gut microbiome'),
    ('Rexulti', 'Brexpiprazole', 'Depression, schizophrenia'),
    ('Tamsulosin', 'Tamsulosin', 'Enlarged prostate, BPH'),
    ('Gabapentin', 'Gabapentin', 'Neuropathy, seizures, nerve pain'),
    ('Olanzapine', 'Olanzapine', 'Bipolar disorder, schizophrenia'),
    ('Sodium Chloride Irrigation Solution', 'Sodium chloride', 'Wound irrigation, nasal irrigation'),
    ('Lidocaine Cream', 'Lidocaine topical', 'Local pain relief, numbing'),
    ('Buspirone', 'Buspirone', 'Anxiety, generalized anxiety disorder'),
    ('Calprotect', 'Barrier cream', 'Skin protection, incontinence care'),
    ('Lidocaine Pain Relief Patch 4%', 'Lidocaine patch', 'Localized pain relief, neuropathy'),
    ('Losartan', 'Losartan', 'High blood pressure, heart failure'),
    ('Metoprolol Tartrate', 'Metoprolol tartrate', 'High blood pressure, heart failure'),
    ('Quetiapine Fumarate', 'Quetiapine fumarate', 'Bipolar disorder, schizophrenia, sleep'),
    ('Tears Drops', 'Artificial tears', 'Dry eyes, eye lubrication'),
    ('Vitamin D3', 'Cholecalciferol', 'Bone health, vitamin D deficiency'),
    ('Iodosorb Gel', 'Cadexomer iodine', 'Wound care, infection prevention'),
    ('Levothyroxine Sodium', 'Levothyroxine sodium', 'Hypothyroidism, thyroid replacement'),
    ('Sertraline', 'Sertraline', 'Depression, anxiety, PTSD'),
    ('Albuterol', 'Albuterol', 'Asthma, COPD, bronchospasm'),
    ('Geri-Tussin', 'Guaifenesin', 'Cough, chest congestion'),
    ('Oxygen (O2)', 'Oxygen', 'Respiratory support, hypoxemia'),
    ('Triad Hydrophilic Wound Dressing Paste', 'Wound dressing paste', 'Wound care, moisture management'),
    ('Thick-It Original Powder', 'Thickening agent', 'Dysphagia, swallowing difficulties'),
    ('Morphine Sulfate', 'Morphine sulfate', 'Severe pain, chronic pain'),
    ('A and D Ointment', 'Vitamins A and D', 'Skin protection, diaper rash'),
    ('Diltiazem', 'Diltiazem', 'High blood pressure, angina'),
    ('Cetaphil Cream', 'Moisturizing cream', 'Dry skin, sensitive skin care'),
    ('Cranberry', 'Cranberry extract', 'UTI prevention, urinary health'),
    ('Meclizine HCL', 'Meclizine hydrochloride', 'Motion sickness, vertigo'),
    ('Phenazopyridine HCL', 'Phenazopyridine hydrochloride', 'Urinary tract pain, dysuria'),
    ('Enema', 'Enema solution', 'Constipation, bowel preparation'),
    ('Gas Relief (Simethicone)', 'Simethicone', 'Gas, bloating, flatulence'),
    ('Guaifenesin', 'Guaifenesin', 'Cough, chest congestion'),
    ('Milk of Magnesia', 'Magnesium hydroxide', 'Constipation, heartburn'),
    ('Ondansetron', 'Ondansetron', 'Nausea, vomiting, chemotherapy nausea'),
]
